name: Check Main Branch Merge

on:
  pull_request:
    branches:
      - release/**

jobs:
  check_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Commit IDs
        id: get_commits
        run: |
          COMMIT_IDS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" | \
                        jq -r '.[].sha')
          echo "::set-output name=commit_ids::${COMMIT_IDS}"

      - name: Check Commits in Main Branch
        run: |
          main_branch="main"
          exit_code=0
          
          IFS=$'\n' read -rd '' -a commit_ids <<<"${COMMIT_IDS}"
          
          echo "Checking commits: ${commit_ids[@]}"
          
          for commit_id in "${commit_ids[@]}"; do
           if ! git branch --contains "$commit_id" | grep -q "$main_branch"; then
               exit_code=1
               echo "Commit $commit_id is not in the $main_branch branch."
               break
           fi
          done
          
          if [ $exit_code -eq 0 ]; then
           echo "All commit IDs are in the $main_branch branch."
          else
           echo "Not all commit IDs are in the $main_branch branch."
           exit 1  # Mark the job as failed
          fi

      - name: Print Commit IDs
        if: always()
        run: | 
          echo "Final Commit IDs: ${{ steps.get_commits.outputs.commit_ids }}"
