name: Check Main Branch Merge

on:
  pull_request:
    branches:
      - release/**

jobs:
  check-main-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Main Branch Merge
        run: |
          #!/bin/bash

          # Fetch all branches and their latest commit hashes
          # git fetch origin "+refs/heads/*:refs/remotes/origin/*" --quiet

          # Check if the pull request contains commits from the main branch
          if git merge-base --is-ancestor origin/main HEAD; then
            echo "PR has been merged into main."
            exit 0
          else
            echo "Error: PR must be merged into main before merging into release."
            exit 1
          fi
